import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav className="flex justify-center gap-4 max-w-4xl mx-auto my-4 pb-2 border-b">
          <Link href="/">Home</Link>
          <Link href="/admin">Admin</Link>
          <Link href="/contact">Contact</Link>
        </nav>
        <main className="max-w-4xl mx-auto">{children}</main>
      </body>
    </html>
  );
}
